name: gawla
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^3.1.0
  dots_indicator: ^1.0.0
  date_picker_timeline: ^1.0.0
  flushbar: ^1.9.0
  circular_profile_avatar: ^1.0.2
  country_code_picker: ^1.1.7
  font_awesome_flutter: ^8.5.0
  animated_text_kit: ^1.3.1
  flutter_open_whatsapp: ^0.1.2
  bubble: ^1.1.9+1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 300
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 600
        - asset: fonts/Poppins/Poppins-Black.ttf
          weight: 900
